spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LS_Application?createDatabaseIfNotExist=true&Unicode=true&serverTimezone=UTC
    username: root
    password: 3DvH*L!z-%srf

  # Show SQL logs

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:

  port: 8080
  servlet:
    context-path: /LSApplication


